# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ben Patterson
email: bmizepatterson@gmail.com
description: Educator, classicist, developer, eater of chocolate
lang: en-US
baseurl: "" # the subpath of your site, e.g. /blog
url: https://bmizepatterson.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: magister_p
github_username:  bmizepatterson
linkedin_username: bmizepatterson
stackoverflow_userid: "6894436"
stackoverflow_username: ben-patterson
google_analytics: UA-124654185-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-sitemap
show_excerpts: true
header_pages:
  - index.md
  - about.md
  - portfolio.html
permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      lang: en-US
      author: Ben Patterson

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%B %e, %Y"

# Jekyll-seo-tag settings
logo: /assets/img/bp_logo.svg
social:
  name: Ben Patterson
  links:
    - https://twitter.com/magister_p
    - https://www.facebook.com/benmizepatterson
    - https://www.linkedin.com/in/bmizepatterson
    - https://github.com/bmizepatterson

# attributes for external links
ext_link_rel: "rel=\"noopener noreferrer\""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
